# Generated by Django 4.2.17 on 2024-12-27 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_brand_category_user_alter_articles_anons_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.CharField(default='11111111', max_length=128),
        ),
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(default='default_username', max_length=100, verbose_name='Имя пользователя'),
            preserve_default=False,
        ),
    ]
